# Generated by Django 4.2 on 2025-08-28 06:16

import apps.products.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("name_az", models.CharField(max_length=300, null=True)),
                ("name_tr", models.CharField(max_length=300, null=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("name_az", models.CharField(max_length=300, null=True)),
                ("name_tr", models.CharField(max_length=300, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                (
                    "price_az",
                    models.DecimalField(
                        decimal_places=2, default=10, max_digits=5, null=True
                    ),
                ),
                (
                    "price_tr",
                    models.DecimalField(
                        decimal_places=2, default=10, max_digits=5, null=True
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=10, max_digits=5),
                ),
                (
                    "discount_az",
                    models.DecimalField(
                        decimal_places=2, default=10, max_digits=5, null=True
                    ),
                ),
                (
                    "discount_tr",
                    models.DecimalField(
                        decimal_places=2, default=10, max_digits=5, null=True
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                ("description_az", ckeditor.fields.RichTextField(null=True)),
                ("description_tr", ckeditor.fields.RichTextField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.products.models.upload_to_products
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Images",
            },
        ),
    ]
