# Generated by Django 4.2 on 2025-08-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=10, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_az",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=10, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount_tr",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=10, max_digits=5, null=True
            ),
        ),
    ]
