# Generated by Django 4.2 on 2025-11-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_choice',
            field=models.CharField(choices=[('akbank', 'Akbank'), ('pasha', 'Pasha'), ('cod', 'Cash on Delivery')], default='cod', max_length=300),
        ),
    ]
