# Generated by Django 4.2 on 2025-11-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('azn', 'AZN'), ('tl', 'TL')], default='azn', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('error', 'Error'), ('success', 'Success')], default='in_progress', max_length=300),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
