# Generated by Django 4.2 on 2026-02-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_currency_order_status_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction',
        ),
        migrations.AddField(
            model_name='order',
            name='order_uuid',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
