# Generated by Django 4.2 on 2026-02-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_transaction_order_order_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_choice',
            field=models.CharField(choices=[('akbank', 'Akbank'), ('pasha', 'Pasha'), ('online', 'Online'), ('cod', 'Cash on Delivery')], default='cod', max_length=300),
        ),
    ]
