# Generated by Django 4.2 on 2026-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_alter_basketitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user_ip',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='basket',
            index=models.Index(fields=['is_active', 'user_ip'], name='baskets_bas_is_acti_c86401_idx'),
        ),
    ]
