# Generated by Django 4.2 on 2026-02-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0006_remove_order_transaction_order_order_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_ip', models.CharField(max_length=500)),
                ('transaction_uuid', models.CharField(max_length=120)),
                ('order_uuid', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('is_completed', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'United Payment Transactions',
            },
        ),
    ]
