# Generated by Django 4.2 on 2025-11-13 09:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='address_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='email_az',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='email_tr',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='facebook_az',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='facebook_tr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_az',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_tr',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone_az',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone_tr',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='short_description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='short_description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='working_hours_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='working_hours_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
