# Generated by Django 4.2 on 2025-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_settings_address_az_settings_address_tr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='tiktok_az',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='tiktok_tr',
            field=models.URLField(blank=True, null=True),
        ),
    ]
