# Generated by Django 4.2 on 2025-11-18 09:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
