# Generated by Django 4.2 on 2026-02-04 07:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='address_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='email_en',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='facebook_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='phone_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='short_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='tiktok_en',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='working_hours_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
