upstream backend {
    server sidra-web:8000;
}

# HTTP Server ONLY for initial certificate issuance
server {
    listen 80;
    server_name sidra-kozmetik.com www.sidra-kozmetik.com;

    # Allow Certbot to verify domain over HTTP
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Everything else proxies to Django
    location / {
        proxy_pass http://backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_redirect off;
    }

    # Static files
    location /staticfiles/ {
        alias /code/sidra/staticfiles/;
    }

    # Media files
    location /mediafiles/ {
        alias /code/sidra/mediafiles/;
    }
}